module NES.Instruction ( decodeOpCode
                       , AddressingMode(..)
                       , InstructionArgument(..)
                       , Instruction(..)
                       ) where

import Data.Word (Word8, Word16)

import NES.CPU

data AddressingMode = Implicit
                    | Accumulator
                    | Immediate
                    | ZeroPage (Maybe Storage)
                    | Relative
                    | Absolute (Maybe Storage)
                    | Indirect (Maybe Storage)

data Mnemonic = ADC | AND | ASL | BCC
              | BCS | BEQ | BIT | BMI
              | BNE | BPL | BRK | BVC
              | BVS | CLC | CLD | CLI
              | CLV | CMP | CPX | CPY
              | DEC | DEX | DEY | EOR
              | INC | INX | INY | JMP
              | JSR | LDA | LDX | LDY
              | LSR | NOP | ORA | PHA
              | PHP | PLA | PLP | ROL
              | ROR | RTI | RTS | SBC
              | SEC | SED | SEI | STA
              | STX | STY | TAX | TAY
              | TSX | TXA | TXS | TYA

data InstructionArgument = Empty | Operand Word8 | Address Word16

data Instruction = Instruction Mnemonic AddressingMode InstructionArgument

decodeOpCode :: Word8 -> (Mnemonic, AddressingMode)
decodeOpCode w =
    case w of
      0x69 -> (ADC, Immediate)
      0x65 -> (ADC, ZeroPage Nothing)
      0x75 -> (ADC, ZeroPage $ Just X)
      0x6D -> (ADC, Absolute Nothing)
      0x7D -> (ADC, Absolute $ Just X)
      0x79 -> (ADC, Absolute $ Just Y)
      0x61 -> (ADC, Indirect $ Just X)
      0x71 -> (ADC, Indirect $ Just Y)
      0x29 -> (AND, Immediate)
      0x25 -> (AND, ZeroPage Nothing)
      0x35 -> (AND, ZeroPage $ Just X)
      0x2D -> (AND, Absolute Nothing)
      0x3D -> (AND, Absolute $ Just X)
      0x39 -> (AND, Absolute $ Just Y)
      0x21 -> (AND, Indirect $ Just X)
      0x31 -> (AND, Indirect $ Just Y)
      0x0A -> (ASL, Accumulator)
      0x06 -> (ASL, ZeroPage Nothing)
      0x16 -> (ASL, ZeroPage $ Just X)
      0x0E -> (ASL, Absolute Nothing)
      0x1E -> (ASL, Absolute $ Just X)
      0x90 -> (BCC, Relative)
      0xB0 -> (BCS, Relative)
      0xF0 -> (BEQ, Relative)
      0x24 -> (BIT, ZeroPage Nothing)
      0x2C -> (BIT, Absolute Nothing)
      0x30 -> (BMI, Relative)
      0xD0 -> (BNE, Relative)
      0x10 -> (BPL, Relative)
      0x00 -> (BRK, Implicit)
      0x50 -> (BVC, Relative)
      0x70 -> (BVS, Relative)
      0x18 -> (CLC, Implicit)
      0xD8 -> (CLD, Implicit)
      0x58 -> (CLI, Implicit)
      0xB8 -> (CLV, Implicit)
      0xC9 -> (CMP, Immediate)
      0xC5 -> (CMP, ZeroPage Nothing)
      0xD5 -> (CMP, ZeroPage $ Just X)
      0xCD -> (CMP, Absolute Nothing)
      0xDD -> (CMP, Absolute $ Just X)
      0xD9 -> (CMP, Absolute $ Just Y)
      0xC1 -> (CMP, Indirect $ Just X)
      0xD1 -> (CMP, Indirect $ Just Y)
      0xE0 -> (CPX, Immediate)
      0xE4 -> (CPX, ZeroPage Nothing)
      0xEC -> (CPX, Absolute Nothing)
      0xC0 -> (CPY, Immediate)
      0xC4 -> (CPY, ZeroPage Nothing)
      0xCC -> (CPY, Absolute Nothing)
      0xC6 -> (DEC, ZeroPage Nothing)
      0xD6 -> (DEC, ZeroPage $ Just X)
      0xCE -> (DEC, Absolute Nothing)
      0xDE -> (DEC, Absolute $ Just X)
      0xCA -> (DEX, Implicit)
      0x88 -> (DEY, Implicit)
      0x49 -> (EOR, Immediate)
      0x45 -> (EOR, ZeroPage Nothing)
      0x55 -> (EOR, ZeroPage $ Just X)
      0x4D -> (EOR, Absolute Nothing)
      0x5D -> (EOR, Absolute $ Just X)
      0x59 -> (EOR, Absolute $ Just Y)
      0x41 -> (EOR, Indirect $ Just X)
      0x51 -> (EOR, Indirect $ Just Y)
      0xE6 -> (INC, ZeroPage Nothing)
      0xF6 -> (INC, ZeroPage $ Just X)
      0xEE -> (INC, Absolute Nothing)
      0xFE -> (INC, Absolute $ Just X)
      0xE8 -> (INX, Implicit)
      0xC8 -> (INY, Implicit)
      0x4C -> (JMP, Absolute Nothing)
      0x6C -> (JMP, Indirect Nothing)
      0x20 -> (JSR, Absolute Nothing)
      0xA9 -> (LDA, Immediate)
      0xA5 -> (LDA, ZeroPage Nothing)
      0xB5 -> (LDA, ZeroPage $ Just X)
      0xAD -> (LDA, Absolute Nothing)
      0xBD -> (LDA, Absolute $ Just X)
      0xB9 -> (LDA, Absolute $ Just Y)
      0xA1 -> (LDA, Indirect $ Just X)
      0xB1 -> (LDA, Indirect $ Just Y)
      0xA2 -> (LDX, Immediate)
      0xA6 -> (LDX, ZeroPage Nothing)
      0xB6 -> (LDX, ZeroPage $ Just Y)
      0xAE -> (LDX, Absolute Nothing)
      0xBE -> (LDX, Absolute $ Just Y)
      0xA0 -> (LDY, Immediate)
      0xA4 -> (LDY, ZeroPage Nothing)
      0xB4 -> (LDY, ZeroPage $ Just X)
      0xAC -> (LDY, Absolute Nothing)
      0xBC -> (LDY, Absolute $ Just X)
      0x4A -> (LSR, Accumulator)
      0x46 -> (LSR, ZeroPage Nothing)
      0x56 -> (LSR, ZeroPage $ Just X)
      0x4E -> (LSR, Absolute Nothing)
      0x5E -> (LSR, Absolute $ Just X)
      0xEA -> (NOP, Implicit)
      0x09 -> (ORA, Immediate)
      0x05 -> (ORA, ZeroPage Nothing)
      0x15 -> (ORA, ZeroPage $ Just X)
      0x0D -> (ORA, Absolute Nothing)
      0x1D -> (ORA, Absolute $ Just X)
      0x19 -> (ORA, Absolute $ Just Y)
      0x01 -> (ORA, Indirect $ Just X)
      0x11 -> (ORA, Indirect $ Just Y)
      0x48 -> (PHA, Implicit)
      0x08 -> (PHP, Implicit)
      0x68 -> (PLA, Implicit)
      0x28 -> (PLP, Implicit)
      0x2A -> (ROL, Accumulator)
      0x26 -> (ROL, ZeroPage Nothing)
      0x36 -> (ROL, ZeroPage $ Just X)
      0x2E -> (ROL, Absolute Nothing)
      0x3E -> (ROL, Absolute $ Just X)
      0x6A -> (ROR, Accumulator)
      0x66 -> (ROR, ZeroPage Nothing)
      0x76 -> (ROR, ZeroPage $ Just X)
      0x6E -> (ROR, Absolute Nothing)
      0x7E -> (ROR, Absolute $ Just X)
      0x40 -> (RTI, Implicit)
      0x60 -> (RTS, Implicit)
      0xE9 -> (SBC, Immediate)
      0xE5 -> (SBC, ZeroPage Nothing)
      0xF5 -> (SBC, ZeroPage $ Just X)
      0xED -> (SBC, Absolute Nothing)
      0xFD -> (SBC, Absolute $ Just X)
      0xF9 -> (SBC, Absolute $ Just Y)
      0xE1 -> (SBC, Indirect $ Just X)
      0xF1 -> (SBC, Indirect $ Just Y)
      0x38 -> (SEC, Implicit)
      0xF8 -> (SED, Implicit)
      0x78 -> (SEI, Implicit)
      0x85 -> (STA, ZeroPage Nothing)
      0x95 -> (STA, ZeroPage $ Just X)
      0x8D -> (STA, Absolute Nothing)
      0x9D -> (STA, Absolute $ Just X)
      0x99 -> (STA, Absolute $ Just Y)
      0x81 -> (STA, Indirect $ Just X)
      0x91 -> (STA, Indirect $ Just Y)
      0x86 -> (STX, ZeroPage Nothing)
      0x96 -> (STX, ZeroPage $ Just Y)
      0x8E -> (STX, Absolute Nothing)
      0x84 -> (STY, ZeroPage Nothing)
      0x94 -> (STY, ZeroPage $ Just X)
      0x8C -> (STY, Absolute Nothing)
      0xAA -> (TAX, Implicit)
      0xA8 -> (TAY, Implicit)
      0xBA -> (TSX, Implicit)
      0x8A -> (TXA, Implicit)
      0x9A -> (TXS, Implicit)
      0x98 -> (TYA, Implicit)
      _ -> error "invalid opCode"
